export const FETCH_MOVIES_REQUEST = 'FETCH_MOVIES_REQUEST'
export const FETCH_MOVIES_SUCCESS = 'FETCH_MOVIES_SUCCESS'
export const FETCH_MOVIES_FAIL = 'FETCH_MOVIES_FAIL'

export const RECOMMEND_MOVIES_REQUEST = 'RECOMMEND_MOVIES_REQUEST'
export const RECOMMEND_MOVIES_SUCCESS = 'RECOMMEND_MOVIES_SUCCESS'
export const RECOMMEND_MOVIES_FAIL = 'RECOMMEND_MOVIES_FAIL'
